-- =============================================================================
-- DCM Project Definition: 01_databases.sql
-- Generated by terraform-to-dcm
-- =============================================================================

DEFINE DATABASE ANALYTICS_DB
  COMMENT = 'Base de datos de analítica';

