-- =============================================================================
-- DCM Project Definition: 02_schemas.sql
-- Generated by terraform-to-dcm
-- =============================================================================

DEFINE SCHEMA ANALYTICS_DB.SALES;

