-- =============================================================================
-- DCM Project Definition: 03_warehouses.sql
-- Generated by terraform-to-dcm
-- =============================================================================

DEFINE WAREHOUSE ANALYTICS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

