-- =============================================================================
-- DCM Project Definition: 04_roles.sql
-- Generated by terraform-to-dcm
-- =============================================================================

DEFINE ROLE ANALYST_ROLE;

