-- =============================================================================
-- DCM Project Definition: 05_tables.sql
-- Generated by terraform-to-dcm
-- =============================================================================

DEFINE TABLE ANALYTICS_DB.SALES.ORDERS (
    id NUMBER(38,0) NOT NULL,
    amount FLOAT,
    date DATE
  );

