-- =============================================================================
-- DCM Project Definition: 08_grants.sql
-- Generated by terraform-to-dcm
-- =============================================================================

GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE ANALYST_ROLE;

